### ISSUE TITLE
php wrapper

### ISSUE THREAD

**Issue by kaysond** [idlesign/deluge-webapi#10]
I made a quick wrapper in php for the json api and included methods from your plugin. It was a bit tough to find documentation for deluge and get this up and running, so maybe a link in your readme could help users?
https://github.com/kaysond/deluge-php

**Comment by idlesign** [comment]
I don't think it quite belongs to readme, so I've added it into docs - http://deluge-webapi.rtfd.io/#more-things
Deluge has a wiki, so you may try also to advertise your app there.

**Comment by kaysond** [comment]
Will do thanks.
