### ISSUE TITLE
Unable to install on deluge 1.3.15

### ISSUE THREAD

**Issue by R3nierjvr** [idlesign/deluge-webapi#16]

**Comment by R3nierjvr** [comment]
Hi
Just tried to install , getting no error just not apearing in my plgins list.
Tried with another plugin https://forum.deluge-torrent.org/viewtopic.php?f=9&t=52115
Other plugin installs fine
Thx

**Comment by idlesign** [comment]
Hi, 
Thank you for the report. We need some debug logs to investigate what is going on. Without it it's hard to say anything. Also sys specs would be great.

See related #15, #16 and maybe #6 if Windows.

**Comment by R3nierjvr** [comment]
will get that thx

**Comment by idlesign** [comment]
Presumably fixed in 0.3.2 (see #21). Closing this.
