### ISSUE TITLE
Empty password not supported

### ISSUE THREAD

**Issue by rozza-m** [idlesign/deluge-webapi#19]
Some users will have ensured security in other ways. It's not possible to have the WebUI passwordless and still use the webapi.

There appears to be a patch [https://forum.deluge-torrent.org/viewtopic.php?t=51155](https://forum.deluge-torrent.org/viewtopic.php?t=51155) but I haven't tried it.

**Comment by dejected1** [comment]
your hyperlink is broken. please repost, i would love to have this patch.

**Comment by rozza-m** [comment]
Edited. However upon slightly closer inspection I think it makes changes to WebUI not WebApi. I am not clever enough to understand why (if this is the case) the webUI will itself permit empty passwords but somehow prevents webui from doing the same.

**Comment by idlesign** [comment]
> [...] I think it makes changes to WebUI not WebApi

Exactly. We may try to use monkeypatching, but I'm not sure it'll work.

**Comment by idlesign** [comment]
Considered closed. 
Feel free to reopen if required.
