### ISSUE TITLE
Get progress

### ISSUE THREAD

**Issue by noamanahmed** [idlesign/deluge-webapi#2]
Hi
Any way to show current progress upload download speed and seeders leechers and time remaining?

**Comment by idlesign** [comment]
Hi,

Yes, probably: `get_torrents` accepts `params` argument and you can supply to it params names to retrieve, e.g.: 'state', 'progress', etc. Yet I can't remember exact names for the params you want, not from the top of my head. You can consult Deluge docs on `get_torrents_status` method.

**Comment by noamanahmed** [comment]
Thanx so much...actually I was looking to get info about a single file

**Comment by idlesign** [comment]
You should consult the built-in API then, I think.

**Comment by noamanahmed** [comment]
can you guide me please...I am kind of a beginner
skype:noamanahmed99

**Comment by idlesign** [comment]
I'm personally do not use the built int Deluge JSON API, so you probably better to post your question on Deluge Forum - http://forum.deluge-torrent.org/viewforum.php?f=8&sid=1d58cb585e03af5ddf13888cb50918e4 and also consult API docs at http://deluge-torrent.org/docs/1.2/modules/ui/web/json_api.html

**Comment by noamanahmed** [comment]
the last parameter id...could you explain how to use it properly

**Comment by idlesign** [comment]
Sorry, the last parameter id of what?

**Comment by noamanahmed** [comment]
np got that sorted...

$post='{"method": "web.get_torrent_status","params":
["'.$file.'",["name","paused","ratio","progress"]], "id": 1}';

can you tell me what I am doing wrong?

**Comment by idlesign** [comment]
You probably could deduce it from server response, yet I see no `get_torrent_status` in http://deluge-torrent.org/docs/1.2/modules/ui/web/json_api.html

**Comment by noamanahmed** [comment]
I have seen the page...Basically The server doesnot give any error but
return the result part to be empty

**Comment by idlesign** [comment]
Some hints:
1. Make sure you logged in;
2. Make sure called method exists;
3. Make sure called method accepts given params.

**Comment by SchizoDuckie** [comment]
Needed this same info.

Found this:

https://github.com/deluge-torrent/deluge/blob/852f6049bd0b5bf31c8c578b8e112108239847ea/deluge/ui/web/js/deluge-all/data/TorrentRecord.js

It would be awesome if you could expand the docs a bit, even if it's just references to files like this that tell what parameters you can use for requests.

**Comment by idlesign** [comment]
@SchizoDuckie The thing is those API methods are not part of `deluge-webapi` — they're shipped with Deluge WebUI and maintained by those other guys %) So only those guys have actual knowledge of current and futher state of API, and it's them who should keep actual documentation.

**Comment by idlesign** [comment]
Considered closed.
Feel free to reopen in required.
