### ISSUE TITLE
Unconsistent API results for seeding torrents

### ISSUE THREAD

**Issue by rob1998** [idlesign/deluge-webapi#20]
Hey I'm a user (and I help the developer) of Organizr, where we use this plugin to connect to deluge and get all active torrents.
I noticed something weird. I have 3 different results for a seeding torrent, only essential info displayed:
Torrent 1 {
    "queue": -1,
    "state": "Seeding",
    "progress": 100
},
Torrent 2 {
    "queue": 62,
    "state": "Seeding",
    "progress": 100
}, 
Torrent 3 {
    "queue": 84,
    "state": "Seeding",
    "progress": 0
}

As I'm writing this issue, everything seems to have returned to normal, but might be worth looking into anyway.

**Comment by idlesign** [comment]
Thank you.
There's nothing webapi could do about: this data come straight from Deluge core.
Closing this.
