### ISSUE TITLE
Unable to pass fields to get_torrents

### ISSUE THREAD

**Issue by blade2005** [idlesign/deluge-webapi#23]
```$ ~/.local/bin/deluge-web.py
WebAPI version: 0.3.2
Success
Number of torrents: 564
Traceback (most recent call last):
  File "/home/<user>/.local/bin/deluge-web.py", line 56, in <module>
    torrents = send_request('webapi.get_torrents', ['hash', 'name', 'save_path', 'comment'])
  File "/home/<user>/.local/bin/deluge-web.py", line 36, in send_request
    raise Exception('API response: %s' % msg)
Exception: API response: get_torrents() takes at most 3 arguments (5 given)
```

Using webapi/test.py and adding the following code 

```
torrents = send_request('webapi.get_torrents')

print('Number of torrents: {}'.format(len(torrents['torrents'])))

torrents = send_request('webapi.get_torrents', ['hash', 'name', 'save_path', 'comment'])

print(torrents)
```

I get the aforementioned error.

My deluge instances run in a docker container, I'm working on getting a way to enable debugging to do more diffing.

**Comment by idlesign** [comment]
Test file is for testing purposes and not to be used as full featured API client: it may or may not support passing arguments to different API methods. Please check ``get_torrents`` expected signature.

**Comment by blade2005** [comment]
https://github.com/idlesign/deluge-webapi/blob/master/webapi/webui.py#L27

**Comment by idlesign** [comment]
That's how it's done in ``torrt``: https://github.com/idlesign/torrt/blob/master/torrt/rpc/deluge.py#L87
Take a look at passed params count.

**Comment by blade2005** [comment]
So it requires a list of params passable. 

Additionally as more information for someone else that happens across this thread. If you provide an alternate list of params it doesn't seem to like an empty ids list.
