### ISSUE TITLE
Can't Activate Plugin [Docker]

### ISSUE THREAD

**Issue by samcro1967** [idlesign/deluge-webapi#29]
I have installed the plugin, but I am not able to activate it.  The checkbox is there, but when I try to click it to put a check into it, nothing happens.  I am able to activate other plugins in, just not this one.

I downloaded "WebAPI-0.4.0-py3.7.egg".  I am running Deluge version 2.0.3-2-201906121747 from the Docker Conmtainer linuxserver/deluge:latest.

Is there something else I am missing?

![image](https://user-images.githubusercontent.com/2319445/85323243-49d05580-b48d-11ea-9c34-9544b598070e.png)

**Comment by idlesign** [comment]
* Is it only Docker or local install reveals the same?
* What's in Deluge daemon log (debug mode) when you try to activate it?
* > The checkbox is there, but when I try to click it to put a check into it, nothing happens.
  
  On your screenshot there's only `WebUi`, but no `WebApi`

On Docker you may also want to see #21

**Comment by samcro1967** [comment]
Geez.  The names are so close I did not notice it was not even loading.

I am running Windows.  Deluge 2.x is only available via Linux so I am not able to test the local install.

After reviewing the other posts, I did determine linuxserver/deluge:latest is running Python 3.6.9.  Switching to WebAPI-0.4.0-py3.6.egg solved the issue.  Thanks!

**Comment by Deus-Rex** [comment]
Just wanted to leave a message here to say that I've just did the exact same thing. Thanks Samcro for making me aware that I was also misreading the plugins.... Hah!
