### ISSUE TITLE
Docker. Unable to open config file /config/webapi.conf

### ISSUE THREAD

**Issue by kriegalex** [idlesign/deluge-webapi#30]
```
             [INFO    ][webapi.core                   :20  ] Enabling WebAPI plugin CORE ...
12:33:48.164 [WARNING ][deluge.config                 :405 ] Unable to open config file /config/webapi.conf: [Errno 2] No such file or 
directory: '/config/webapi.conf'
12:33:48.164 [INFO    ][deluge.pluginmanagerbase      :189 ] Plugin WebAPI enabled...
```
I just checked and my /config is chmod 777

![image](https://user-images.githubusercontent.com/2486182/100606321-88eeb680-3309-11eb-8ec4-d3d65673ca71.png)

It seems like it is unable to create the webapi.conf file, weird... I have tried restarting deluge. I'm using deluge in a docker from binhex/arch-delugevpn

**Comment by idlesign** [comment]
Please have a look at #21, that may be interesting.
Please verify that the same can be reproduced without Docker.
Meanwhile closing this as not related to the plugin itself.
