### ISSUE TITLE
Get torrent status

### ISSUE THREAD

**Issue by NikDevx** [idlesign/deluge-webapi#31]
Hello 
Is it possible to get torrent status? 
I mean downloading, downloaded, pause and etc.

**Comment by idlesign** [comment]
Hi,

Sure, and you even don't need this `webapi` extension, since Deluge JSON API already has `.get_torrent_status()` method.
See for details: https://deluge.readthedocs.io/en/latest/reference/webapi.html

**Comment by NikDevx** [comment]
> Hi,
> 
> Sure, and you even don't need this `webapi` extension, since Deluge JSON API already has `.get_torrent_status()` method. See for details: https://deluge.readthedocs.io/en/latest/reference/webapi.html

Thanks
