### ISSUE TITLE
Request method CORS conditional failing on Deluge 2.1.1

### ISSUE THREAD

**Issue by griest024** [idlesign/deluge-webapi#34]
On Deluge 2.1.1, the [twisted request method is of type bytes](https://docs.twisted.org/en/stable/api/twisted.web.http.Request.html#method), not string. Therefore https://github.com/idlesign/deluge-webapi/blob/9d87b79bd108185ee1d8c05af415d0613d4dbbf6/webapi/core.py#L83

fails because `request.method` is actually `b'OPTIONS'`.

**Comment by griest024** [comment]
and FWIW https://github.com/idlesign/deluge-webapi/blob/9d87b79bd108185ee1d8c05af415d0613d4dbbf6/webapi/core.py#L95 should be `request.write(b'')`

**Comment by idlesign** [comment]
Pull request in a backward-compatible manner is welcome.
