### ISSUE TITLE
web.add_torrents should return the ID of the added torrent

### ISSUE THREAD

**Issue by sormu** [idlesign/deluge-webapi#5]
When adding a torrent, some options must be set using set_config, since they can't be set when adding the torrent.

In the ideal world all params of set_config, should be available when using add_torrents, but for now it returning the ID's of the added torrents would be a working solution.

**Comment by idlesign** [comment]
ID might be a torrent hash (if I'm not mistaken, need to verify it though), which is freely available both from magnet link and torrent file, so you already know it and can address torrent you want.

Yet indeed we probably could return it from `add_torrent` just to make things simplier.

I'll pick into Deluge if I have time.
Thank you for that proposal.

**Comment by sormu** [comment]
Yes, but then if i would change in deluge for some reason my stuff would break - best experience would be that i didnt have to worry about it

**Comment by idlesign** [comment]
Seems to be implemented.
You can verify it by building an .egg  from `master` branch and installing it.
